// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhanwvqujchafxaijujv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYW53dnF1amNoYWZ4YWlqdWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTA0MzAsImV4cCI6MjA3MDIyNjQzMH0.Epdl5bcu2OR5VcOTd_kuZ3PV8814rf2ru9OWg1u5aJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});